services:
    px4-gazebo-classic:
        image: px4-gazebo-classic
        build:
            context: .
            dockerfile: Dockerfile
            args:
              - DOCKER_BUILDKIT=1
        container_name: px4-gazebo-classic_cnt
        tty: true
        stdin_open: true
        privileged: true
        network_mode: host
        working_dir: /root
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=$XAUTHORITY
            - GAZEBO_PLUGIN_PATH=/root/src/sitl_gazebo/build
            - GAZEBO_MODEL_PATH=/root/src/sitl_gazebo/models
            - GAZEBO_MODEL_DATABASE_URI=""
            - SITL_GAZEBO_PATH=root/src/sitl_gazebo
        volumes:
            - $XAUTHORITY:$XAUTHORITY
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/sudoers.d:/etc/sudoers.d:ro
            - /dev:/dev
            - $PWD/../../PX4-SITL_gazebo-classic:/root/src/sitl_gazebo
        security_opt:
            - seccomp:unconfined
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

